# .gitignore

Android.gitignore is a sample .gitignore file copied from [https://github.com/github/gitignore][0]

You add it to the root of your Android project folder and it will ignore any generated by Eclipse

Example:
/path/to/MyAndroidProject/.gitignore

[0]: https://github.com/github/gitignore
